name: kiit_archives
version: 1.0.2+2
description: A new Flutter application.
environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Project Structure
  get: 4.1.4

  # Authentication
  firebase_auth: ^1.2.0

  # Icons
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
