name: kiit_app
version: 1.0.2+2
description: A new Flutter application.
environment: 
  sdk: '>=2.13.0 <3.0.0'

dependencies: 
  cupertino_icons: ^0.1.2
  get: 4.1.4
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

