name: kiit_archives
version: 1.0.2+2
description: A new Flutter application.
environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #UI
  animations: ^2.0.0

  # Project Structure
  get: 4.1.4

  # Authentication
  firebase_auth: ^1.2.0
  firebase_core: ^1.2.0
  google_sign_in: ^5.0.4
  firebase_storage: ^8.1.1
  path_provider: ^2.0.2
  cloud_firestore: ^2.2.1
  # googleapis: ^3.0.0
  # googleapis_auth: ^1.1.0
  # flutter_secure_storage: ^4.2.0
  # oauth2_client: ^2.2.0
  # url_launcher: ^6.0.5
  # drive_helper: ^1.2.6
  # Icons
  # cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
